### ISSUE TITLE
Failing on Lambda due to missing Class

### ISSUE THREAD

**Issue by nblumoe** [mhjort/clojider#12]
Thanks for Clojider and clj-gatling!

I run into the following exception when trying to run my own simulations on Lambda:

```
Caused by: java.lang.ClassNotFoundException: scala.collection.mutable.HashMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
	at clojider_gatling_highcharts_reporter.generator$loading__5569__auto____1078.invoke(generator.clj:1)
	at clojider_gatling_highcharts_reporter.generator__init.load(Unknown Source)
	at clojider_gatling_highcharts_reporter.generator__init.<clinit>(Unknown Source)
```
This is from the Lambda logs. On the client where I init the run, it surfaces like this:
```
$ lein run load-lambda -r eu-west-1 -b nblumoe-load-testing -c 1 -d 6 -s nblumoe.gatling/read-only-simulation
Running simulation nblumoe.gatling/read-only-simulation with options {:concurrency 1, :nodes 1, :timeout 5000, :duration #object[org.joda.time.Seconds 0x3ec8c874 PT6S], :region eu-west-1, :bucket nblumoe-load-testing, :simulation nblumoe.gatling/read-only-simulation}
Starting AWS Lambda executor with id: 0
Invoking Lambda for node: 0
nblumoe-load-testing already exists. Skipping creation.
Downloading nil from nblumoe-load-testing
Parsing log file(s)...
19:13:42.770 [main] INFO  i.g.c.result.reader.FileDataReader - Collected List() from input
Syntax error (IllegalArgumentException) compiling at (/private/var/folders/rm/7dw9bw5d5pj7lg41n5j77mww0000gn/T/form-init6743625326106399828.clj:1:125).
requirement failed: simulation directory doesn't contain any log file.
```

I have `  :uberjar-exclusions [#"scala.*"]` in the `project.clj` and updates the standalone jar on S3.

I don't get the error from above when a run an example simulation though:

`$ lein run load-lambda -r eu-west-1 -b nblumoe-load-testing -c 1 -d 6 -s clojider.examples/ping-simulation`

Am I missing something in my setup?

**Comment by nblumoe** [comment]
I figured it out: I must not require `clj-gatling` from the scenario defining namespace.

**Comment by grav** [comment]
This didn't fix it for me - I needed to remove the `:uberjar-exclusions [#"scala.*"]` from my `project.clj`.
