### ISSUE TITLE
Setup issue -- The role defined for the function cannot be assumed by Lambda

### ISSUE THREAD

**Issue by jonmarkprice** [mhjort/clojider#8]
Hi, I am trying to set up Clojider and keep running into this issue with the IAM Roles. 

```
Creating role clojider-role-us-east-1 with policy clojider-policy-us-east-1
clojider already exists. Skipping creation.
Uploading code to S3 from target/try-clojider-0.1.0-SNAPSHOT.jar
Creating Lambda function clojider-load-testing-lambda to region us-east-1
Exception in thread "main" com.amazonaws.services.lambda.model.InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: fa3482ad-2d7c-11e8-aa56-29beccbd238b), compiling:(/private/var/folders/f9/s61lc0fn6ss1_fsy7f1yhg2h0000gn/T/form-init7247895295587934841.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```
This was run with:
```
lein run install -r us-east-1 -b clojider -f target/try-clojider-0.1.0-SNAPSHOT.jar
```

I am have the region set in `~/.aws/config` 

```
[default]
region = us-east-1
```
and credentials at `~/.aws/credentials`. 

Thanks,
Jonathan

**Comment by mhjort** [comment]
Hi, sounds really weird. I have never seen such an error. I just tried to install my test Lambda function and it  worked fine. I did some googling and found that other people have had similar temporarily issues. See https://forums.aws.amazon.com/message.jspa?messageID=747234. Could you try it again now? Have you tried creating Lambda functions manually with your credentials? Just to verify that you have correct access rights for creating Lambda functions.

**Comment by jonmarkprice** [comment]
Hi Thanks for the response. I just tried again from a clean repository and am getting the same error. I can create Lambda functions manually using the role Clojider created (`clojider-role-us-east-1`) and run them. 
I am new to lein and clojure (installed both for this) so it is quite possible I set things up incorrectly. 

My `project.clj` looks like this:
```
(defproject retry-clojider "0.1.0-SNAPSHOT"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"] [clojider "0.4.6"]]
  :main clojider.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  :uberjar-exclusions [#"scala.*"])
```

I created by running `lein new app retry-clojider` then manually editing the `project.clj` it created. Then I ran:
```
lein uberjar
lein run install -r us-east-1 -b clojider-bucket -f target/uberjar/retry-clojider-0.1.0-SNAPSHOT.jar 
```

I got a warning from `lein uberjar`:
```
Compiling retry-clojider.core
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method, or the namespace has not been AOT-compiled.
Created /Users/jon/repos/retry-clojider/target/uberjar/retry-clojider-0.1.0-SNAPSHOT.jar
Created /Users/jon/repos/retry-clojider/target/uberjar/retry-clojider-0.1.0-SNAPSHOT-standalone.jar
```
Am I missing some command to pull clojider from clojars or something (a la `npm install`)?

**Comment by mhjort** [comment]
Hi,

could you try adding this setting to your `project.clj`?

```
 :aot [clojider.core clojider.lambda]
```

Also I just made a small bug fix release `0.4.7`. If you could try with that?

**Comment by jonmarkprice** [comment]
Hi Markus,

Sorry for taking so long to get back to you. 

I'm still getting the same `InvalidParameterValueException` error with 0.4.7 and that line.

<details>
<summary>Expand full exception</summary>
<pre>
Exception in thread "main" com.amazonaws.services.lambda.model.InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a1acdfde-3643-11e8-8a07-11241ef8fd95), compiling:(/private/var/folders/f9/s61lc0fn6ss1_fsy7f1yhg2h0000gn/T/form-init670936404811078754.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: com.amazonaws.services.lambda.model.InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a1acdfde-3643-11e8-8a07-11241ef8fd95)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1925)
	at com.amazonaws.services.lambda.AWSLambdaClient.createFunction(AWSLambdaClient.java:686)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at clojider.aws$create_lambda_fn.invokeStatic(aws.clj:118)
	at clojider.aws$create_lambda_fn.invoke(aws.clj:115)
	at clojider.aws$install_lambda.invokeStatic(aws.clj:135)
	at clojider.aws$install_lambda.invoke(aws.clj:129)
	at clojider.core$_main.invokeStatic(core.clj:56)
	at clojider.core$_main.doInvoke(core.clj:52)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at clojure.lang.Var.invoke(Var.java:419)
	at user$eval5.invokeStatic(form-init670936404811078754.clj:1)
	at user$eval5.invoke(form-init670936404811078754.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
</pre>
</details>

It's probably something with my AWS setup, rather than Clojider since it's not duplicating. 
Thanks for your help :)

**Comment by petterik** [comment]
I'm having the same issue with `[clojider "0.5.0"]` and I've tried both `:aot :all` and `:aot [clojider.core clojider.lambda]`. 

@jonmarkprice Did you solve this problem?

**Comment by jonmarkprice** [comment]
@petterik No, I didn't ever get it to work, sorry

**Comment by petterik** [comment]
@jonmarkprice That's too bad! Good news! We got it to work by introducing a sleep between the "policy & role" creation and the lambda creation.

We tried this because of the discussion in this issue: https://github.com/Miserlou/Zappa/issues/249

Will send a pull request with an ~configurable~ amount of sleep. Maybe a better solution can be done later.

**Comment by laudiacay** [comment]
I just got this on 0.47.1, by the way- I believe it is still that race condition, because I ran deploy again after getting the error and it succeeded.
